=== DuinoPack/v1.2/linux/DuinoPack.v1.2.Linux/hardware/tools/g++_arm_none_eabi/arm-none-eabi/lib/boards/board.dtd
<!-- Board description files

     Copyright (c) 2007-2009 CodeSourcery, Inc.

     THIS FILE CONTAINS PROPRIETARY, CONFIDENTIAL, AND TRADE
     SECRET INFORMATION OF CODESOURCERY AND/OR ITS LICENSORS.

     You may not use or distribute this file without the express
     written permission of CodeSourcery or its authorized
     distributor.  This file is licensed only for use with 
     Sourcery G++.  No other use is permitted.
     -->

<!ELEMENT board
	(properties?, feature?, initialize?, memory-map?)>

<!ELEMENT properties
	(description?, property*)>

<!ELEMENT initialize
	(write-register | write-memory | delay
	 | wait-until-memory-equal | wait-until-memory-not-equal)* >
<!ELEMENT write-register EMPTY>
<!ATTLIST write-register
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        bits    CDATA   #IMPLIED>
<!ELEMENT write-memory EMPTY>
<!ATTLIST write-memory
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        bits    CDATA   #IMPLIED>
<!ELEMENT delay EMPTY>
<!ATTLIST delay
		        time CDATA   #REQUIRED>
<!ELEMENT wait-until-memory-equal EMPTY>
<!ATTLIST wait-until-memory-equal
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        timeout CDATA   #IMPLIED
                        bits    CDATA   #IMPLIED>
<!ELEMENT wait-until-memory-not-equal EMPTY>
<!ATTLIST wait-until-memory-not-equal
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        timeout CDATA   #IMPLIED
                        bits    CDATA   #IMPLIED>

<!ELEMENT memory-map (memory-device)*>
<!ELEMENT memory-device (property*, description?, sectors*)>
<!ATTLIST memory-device
                        address CDATA   #REQUIRED
		        size    CDATA   #REQUIRED
		        type    CDATA   #REQUIRED
                        device  CDATA   #IMPLIED>

<!ELEMENT description (#PCDATA)>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>
<!ELEMENT sectors EMPTY>
<!ATTLIST sectors
	size CDATA #REQUIRED
	count CDATA #REQUIRED>

<!ENTITY % gdbtarget SYSTEM "gdb-target.dtd">
%gdbtarget;

=== DuinoPack/v1.2/linux/DuinoPack.v1.2.Linux/hardware/tools/g++_arm_none_eabi/arm-none-eabi/lib/boards/cycloneiii-cm1.xml
<?xml version="1.0"?>
<!DOCTYPE board SYSTEM "board.dtd">
<!-- Description for Altera Cyclone III Cortex-M1

     Version: Sourcery G++ Lite 2010q1-188
     Support: https://support.codesourcery.com/GNUToolchain/

     Copyright (c) 2007, 2008, 2009, 2010 CodeSourcery, Inc.

     THIS FILE CONTAINS PROPRIETARY, CONFIDENTIAL, AND TRADE SECRET
     INFORMATION OF CODESOURCERY AND/OR ITS LICENSORS.

     You may not use or distribute this file without the express written
     permission of CodeSourcery or its authorized distributor.  This file is
     licensed only for use with Sourcery G++.  No other use is permitted.
     -->
<board>
  <properties>
    <property name="system-v6-m"/>
  </properties>
  <memory-map>
    <memory-device address="0x00000000" size="32K" type="ram">
      <description>
	ITCM
      </description>
    </memory-device>
    <memory-device address="0x20100000" size="1M" type="ram">
      <description>
	SRAM
      </description>
    </memory-device>
    <memory-device address="0x60000000" size="16M" type="flash" device="cfi">
      <description>
	Flash
      </description>
    </memory-device>
  </memory-map>
</board>
<!-- checksum: 50d29b12de31e7084b6eae -->
